spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.security.password.pepper=PmIdBMxt1xbsdDxCjLRh8ZwoufOsgeeyco5wulRVxtgs

# JWT — Access Token (1 hora)
app.security.jwt.secret=d3v-jwt-s3cr3t-spring-commerce-2026-local-test-only-not-for-prod
app.security.jwt.access-token.expiration-seconds=3600
# JWT — Refresh Token (7 dias)
app.security.jwt.refresh-token.expiration-seconds=604800